---
repository:
  auto_init: true
  license_template: mit
  name: settings
  description: A template repo for repo settings
  homepage: https://settings.irishlab.io/
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled

collaborators:
  - username: irish1986
    permission: admin

teams:
  - name: core
    permission: admin
  - name: docs
    permission: push

environments:
  - name: prod
    wait_timer: 0
    prevent_self_review: true
    reviewers:
      - type: irish1986
        id: 13018674
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_signatures: true
        require_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
