---
name: Continous Integration - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/admin/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  pre-commit:
    needs:
      - secret
    name: Call Pre-Commit for private repo
    uses: irishlab-io/admin/.github/workflows/reusable-pre-commit.yml@main

  hello-world:
    needs:
      - pre-commit
      - secret
    name: Call Hello World
    uses: irishlab-io/admin/.github/workflows/reusable-hello-world.yml@main
    with:
      comments: "4321tset"
      enable: false

  docker-build:
    name: Call Docker Build
    uses: irishlab-io/admin/.github/workflows/reusable-docker-build.yml@main

    needs:
      - pre-commit
      - secret

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      context: "./docker/"
      image-names: |
        ghcr.io/${{ github.repository }}
