---
name: Continous Integration - Pull Request

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/admin/.github/workflows/reusable-secret.yml@main

    secrets: inherit

  pre-commit:
    name: Call Pre-Commit for private repo
    uses: irishlab-io/admin/.github/workflows/reusable-pre-commit.yml@main

    needs:
      - secret

  hello-world:
    name: Call Hello World
    uses: irishlab-io/admin/.github/workflows/reusable-hello-world.yml@main

    needs:
      - pre-commit
      - secret

    with:
      comments: "4321tset"
      enable: false

  docker-build-push:
    name: Call Docker Build
    uses: irishlab-io/admin/.github/workflows/reusable-docker-build.yml@main

    needs:
      - pre-commit
      - secret

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      context: "./docker/"

  scan-image:
    name: Call Trivy Image Scan 
    uses: irishlab-io/admin/.github/workflows/reusable-image-scan.yml@main

    needs:
      - docker-build-push

    permissions: read-all

    with:
      image: "ghcr.io/irishlab-io/nginx-hw:latest" #need to fix this
      # exit-code: 1
      # severity: "LOW,MEDIUM,HIGH,CRITICAL"
      # ignore-unfixed: false
